import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import ordersRouter from "./orders";
import cartRouter from "./cart";
import commissionsRouter from "./commissions";
import genealogyRouter from "./genealogy";
import walletRouter from "./wallet";
import bookingsRouter from "./bookings";
import messagesRouter from "./messages";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import storageRouter from "./storage";
import bppRouter from "./bpp";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import visionGoalsRouter from "./vision_goals";
import dollarCreditsRouter from "./dollar_credits";
import paymentsRouter from "./payments";
import paypalRouter from "./paypal";
import authorizeNetRouter from "./authorizenet";
import bookingPayoutsRouter from "./booking-payouts";
import proPackagesRouter from "./pro-packages";
import bannersRouter from "./banners";
import nonprofitRequestsRouter from "./nonprofit-requests";
import subscriptionsRouter from "./subscriptions";
import paygRouter from "./payg";
import sportsTeamsRouter from "./sports-teams";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(ordersRouter);
router.use(cartRouter);
router.use(commissionsRouter);
router.use(genealogyRouter);
router.use(walletRouter);
router.use(bookingsRouter);
router.use(messagesRouter);
router.use(settingsRouter);
router.use(dashboardRouter);
router.use(storageRouter);
router.use(bppRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(visionGoalsRouter);
router.use(dollarCreditsRouter);
router.use(paymentsRouter);
router.use(paypalRouter);
router.use(authorizeNetRouter);
router.use(bookingPayoutsRouter);
router.use(proPackagesRouter);
router.use(bannersRouter);
router.use(nonprofitRequestsRouter);
router.use(subscriptionsRouter);
router.use(paygRouter);
router.use(sportsTeamsRouter);

export default router;
