// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nfgn-home/Redesign.tsx": () => import("../components/mockups/nfgn-home/Redesign.tsx"),
  "./components/mockups/nfgn-theme-compare/Dark.tsx": () => import("../components/mockups/nfgn-theme-compare/Dark.tsx"),
  "./components/mockups/nfgn-theme-compare/Light.tsx": () => import("../components/mockups/nfgn-theme-compare/Light.tsx"),
  "./components/mockups/cashapp-checkout/OptionA.tsx": () => import("../components/mockups/cashapp-checkout/OptionA.tsx"),
  "./components/mockups/cashapp-checkout/OptionB.tsx": () => import("../components/mockups/cashapp-checkout/OptionB.tsx")
};
