// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/cashapp-checkout/OptionA.tsx": () => import("../components/mockups/cashapp-checkout/OptionA.tsx"),
  "./components/mockups/cashapp-checkout/OptionB.tsx": () => import("../components/mockups/cashapp-checkout/OptionB.tsx"),
  "./components/mockups/nfgn-home/HomeA.tsx": () => import("../components/mockups/nfgn-home/HomeA.tsx"),
  "./components/mockups/nfgn-home/HomeB.tsx": () => import("../components/mockups/nfgn-home/HomeB.tsx"),
  "./components/mockups/nfgn-home/HomeC.tsx": () => import("../components/mockups/nfgn-home/HomeC.tsx"),
  "./components/mockups/nfgn-home/HomeD.tsx": () => import("../components/mockups/nfgn-home/HomeD.tsx"),
  "./components/mockups/nfgn-home/Redesign.tsx": () => import("../components/mockups/nfgn-home/Redesign.tsx"),
  "./components/mockups/nfgn-shop/ShopRedesign.tsx": () => import("../components/mockups/nfgn-shop/ShopRedesign.tsx"),
  "./components/mockups/mynfgn-landing/Landing.tsx": () => import("../components/mockups/mynfgn-landing/Landing.tsx"),
  "./components/mockups/nfgn-theme-compare/Dark.tsx": () => import("../components/mockups/nfgn-theme-compare/Dark.tsx"),
  "./components/mockups/nfgn-theme-compare/Light.tsx": () => import("../components/mockups/nfgn-theme-compare/Light.tsx")
};
